image: node:latest

stages:
  - build
  - test

before_script:
  - yarn install --frozen-lockfile --cache-folder .yarn

eslint:
  stage: test
  script:
    - yarn run lint

jest:
  stage: test
  script:
    - yarn test
